name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yaml
          cache-environment: true
      - name: Lint (pyflakes rules)
        run: micromamba run -n miraca ruff check src tests --select F
      - name: Unit tests
        run: micromamba run -n miraca pytest tests
